version: '3'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "3001:3001"
      
  database:
    image: mongo:4.4
    container_name: ci-cd-database
    ports:
      - "27017:27017"
