version: '3'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - database

  web:
    build: ./web
    ports:
      - "3000:3000"

  database:
    image: mongo:4.4
    container_name: ci-cd-database
    ports:
      - "27017:27017"
