name: CI/CD Pipeline

on:
  push:
    branches: [main, feature/*]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and build
      working-directory: web
      run: 
        npm install
        npm run build 
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: web
      run: npm install

    - name: Run tests
      working-directory: web
      run: npm test 

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Firebase CLI
      working-directory: web
      run: npm install -g firebase-tools

    - name: Login to Firebase
      run: firebase login:ci --token $FIREBASE_TOKEN  # Brug det gemte Firebase-token

    - name: Deploy to Firebase
      run: |
        firebase deploy --token $FIREBASE_TOKEN --project <your-project-id>
